# Generated by Django 4.0.3 on 2022-03-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_jobpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePost',
        ),
    ]
