# Generated by Django 4.0.3 on 2022-03-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_activitytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytype',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
