# Generated by Django 4.0.3 on 2022-03-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_title_activitytype_name_jobpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.activitytype'),
        ),
    ]
