# Generated by Django 4.0.3 on 2022-03-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_gamepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePost',
        ),
    ]
