# Generated by Django 4.0.3 on 2022-03-13 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_alter_jobpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bungiename', models.CharField(default='BungieID#1111', max_length=100, unique=True)),
                ('img', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=500)),
                ('bungieID', models.CharField(max_length=100)),
                ('bungieIDLong', models.CharField(max_length=100)),
                ('gamertag', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
