# Generated by Django 4.0.3 on 2022-03-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_gprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gprofile',
            name='img',
            field=models.CharField(default='https://www.bungie.net/img/profile/avatars/bungie_day_15_29.jpg', max_length=500),
        ),
    ]
