# Generated by Django 4.0.3 on 2022-03-16 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='username',
        ),
    ]
